"""Reference implementation for the OnceMesh Action Protocol v0."""

__version__ = "0.1.0"

from .cache import (
    LookupOutcome,
    Policy,
    candidate_for_revalidation,
    publish_invalidation,
    publish_result,
    publish_signed_result,
    reuse,
)
from .canonical import (
    CanonicalizationError,
    action_digest,
    canonical_json,
    digest_bytes,
    invalidation_digest,
    manifest_digest,
    validation_digest,
    validate_action,
    validate_invalidation,
    validate_manifest,
    validate_source_validation,
)
from .store import FilesystemStore, MemoryStore, StoreReadError
from .coordination import CoordinationTimeoutError, ProcessFileLock
from .metrics import EvaluationEvent, InMemoryMetrics, JsonlMetrics, read_jsonl, summarize
from .shadow import ShadowOutcome, run_shadow
from .conditional import run_conditional_http_shadow
from .policy import FilePolicyRegistry, OperationPolicy, PolicyResolution, validate_policy_document
from .runtime import (
    DeterministicExecutionOutcome,
    HttpExecutionOutcome,
    execute_deterministic_with_policy,
    execute_http_with_policy,
)
from .receipt import (
    raw_public_key,
    receipt_digest,
    receipt_signing_input,
    sign_receipt,
    validate_receipt,
    verify_receipt,
    verify_receipt_for_manifest,
)
from .key_registry import (
    FileReceiptKeyRegistry,
    ReceiptKey,
    ReceiptKeyResolution,
    encode_public_key,
    validate_key_registry,
)
from .authorization import (
    authorization_partitions_match,
    derive_authorization_partition,
    validate_authorization_partition,
)
from .revalidation import RevalidationCoordinator, SingleFlightRevalidator, revalidate_http_candidate
from .federation import (
    FederationBundle,
    FederationCacheStore,
    FilesystemFederationCacheStore,
    FederationImportOutcome,
    FederationPeerConfig,
    PublicPeerCatalog,
    availability_signing_input,
    import_from_peer,
    sign_availability,
    validate_availability,
    verify_availability,
)
from .federation_http import (
    EMPTY_BODY_DIGEST,
    FEDERATION_REQUEST_DOMAIN,
    FederationHTTPServer,
    FederationRequestAuthenticator,
    FederationRequestRateLimiter,
    FederationRequesterConfig,
    HttpFederationPeer,
    federation_request_signing_input,
    sign_federation_request,
    validate_federation_request,
    verify_federation_request,
)
from .execution_cache import (
    EncodedExecutionValue,
    ExecutionCacheBridge,
    ExecutionCacheKey,
    FilesystemEpochRegistry,
    MemoryEpochRegistry,
    pack_execution_value,
    unpack_execution_value,
)
from .integrations.base import RuntimeCacheAdapter, RuntimeCallOutcome, RuntimeValueCodec
from .integrations.codecs import JsonValueCodec
from .integrations.index import (
    FilesystemActiveKeyIndex,
    IndexedRuntimeCacheAdapter,
    MemoryActiveKeyIndex,
    SQLiteActiveKeyIndex,
)
from .integrations.python import PYTHON_JSON_SERIALIZER, OnceMeshPythonCache, PythonJsonCodec
from .integrations.registry import (
    AdapterDescriptor,
    builtin_adapters,
    discover_adapters,
    get_adapter,
    load_adapter_class,
)
from .discovery import (
    MAX_DIRECTORY_BYTES,
    MESH_STATUSES,
    PUBLIC_DIRECTORY_URL,
    PUBLIC_DIRECTORY_VERSION,
    fetch_public_mesh_directory,
    load_public_mesh_directory,
    parse_public_mesh_directory,
    search_public_meshes,
    validate_public_mesh_directory,
)
from .mesh_status import (
    PUBLIC_MESH_STATUS_VERSION,
    generate_public_mesh_status,
    validate_public_mesh_status,
    write_public_mesh_status,
)

__all__ = [
    "__version__",
    "CanonicalizationError",
    "LookupOutcome",
    "FilesystemStore",
    "EvaluationEvent",
    "FilePolicyRegistry",
    "InMemoryMetrics",
    "JsonlMetrics",
    "HttpExecutionOutcome",
    "DeterministicExecutionOutcome",
    "MemoryStore",
    "Policy",
    "OperationPolicy",
    "PolicyResolution",
    "StoreReadError",
    "CoordinationTimeoutError",
    "ProcessFileLock",
    "ShadowOutcome",
    "action_digest",
    "candidate_for_revalidation",
    "canonical_json",
    "digest_bytes",
    "manifest_digest",
    "validation_digest",
    "invalidation_digest",
    "publish_invalidation",
    "publish_result",
    "publish_signed_result",
    "reuse",
    "run_shadow",
    "run_conditional_http_shadow",
    "execute_http_with_policy",
    "execute_deterministic_with_policy",
    "read_jsonl",
    "summarize",
    "validate_action",
    "validate_invalidation",
    "validate_manifest",
    "validate_source_validation",
    "validate_policy_document",
    "raw_public_key",
    "receipt_digest",
    "receipt_signing_input",
    "sign_receipt",
    "validate_receipt",
    "verify_receipt",
    "verify_receipt_for_manifest",
    "FileReceiptKeyRegistry",
    "ReceiptKey",
    "ReceiptKeyResolution",
    "encode_public_key",
    "validate_key_registry",
    "authorization_partitions_match",
    "derive_authorization_partition",
    "validate_authorization_partition",
    "RevalidationCoordinator",
    "SingleFlightRevalidator",
    "revalidate_http_candidate",
    "FederationBundle",
    "FederationCacheStore",
    "FilesystemFederationCacheStore",
    "FederationImportOutcome",
    "FederationPeerConfig",
    "PublicPeerCatalog",
    "availability_signing_input",
    "import_from_peer",
    "sign_availability",
    "validate_availability",
    "verify_availability",
    "EMPTY_BODY_DIGEST",
    "FEDERATION_REQUEST_DOMAIN",
    "FederationHTTPServer",
    "FederationRequestAuthenticator",
    "FederationRequestRateLimiter",
    "FederationRequesterConfig",
    "HttpFederationPeer",
    "federation_request_signing_input",
    "sign_federation_request",
    "validate_federation_request",
    "verify_federation_request",
    "EncodedExecutionValue",
    "ExecutionCacheBridge",
    "ExecutionCacheKey",
    "FilesystemEpochRegistry",
    "MemoryEpochRegistry",
    "pack_execution_value",
    "unpack_execution_value",
    "RuntimeCacheAdapter",
    "RuntimeCallOutcome",
    "RuntimeValueCodec",
    "PYTHON_JSON_SERIALIZER",
    "OnceMeshPythonCache",
    "PythonJsonCodec",
    "JsonValueCodec",
    "FilesystemActiveKeyIndex",
    "IndexedRuntimeCacheAdapter",
    "MemoryActiveKeyIndex",
    "SQLiteActiveKeyIndex",
    "AdapterDescriptor",
    "builtin_adapters",
    "get_adapter",
    "discover_adapters",
    "load_adapter_class",
    "MAX_DIRECTORY_BYTES",
    "MESH_STATUSES",
    "PUBLIC_DIRECTORY_URL",
    "PUBLIC_DIRECTORY_VERSION",
    "fetch_public_mesh_directory",
    "load_public_mesh_directory",
    "parse_public_mesh_directory",
    "search_public_meshes",
    "validate_public_mesh_directory",
    "PUBLIC_MESH_STATUS_VERSION",
    "generate_public_mesh_status",
    "validate_public_mesh_status",
    "write_public_mesh_status",
]
